export const protocols = [
  { id: 1, name: "lido" },
  { id: 2, name: "anchor" },
  { id: 3, name: "astroport" },
  { id: 4, name: "wormhole" },
  { id: 5, name: "terraswap" },
  { id: 6, name: "prism-protocol" },
  { id: 7, name: "allbridge" },
  { id: 8, name: "mars-protocol" },
  { id: 9, name: "pylon-protocol" },
  { id: 10, name: "spectrum-protocol" },
  { id: 11, name: "loop-finance" },
  { id: 12, name: "nexus-protocol" },
  { id: 13, name: "white-whale" },
  { id: 14, name: "edge-protocol" },
  { id: 15, name: "apollodao" },
  { id: 16, name: "starterra" },
  { id: 17, name: "risk-harbor" },
  { id: 18, name: "ink-protocol" },
  { id: 19, name: "loterra" },
  { id: 20, name: "terrafloki" },
  { id: 21, name: "valkyrie" },
  { id: 22, name: "stader" },
  { id: 23, name: "mirror" },
  { id: 24, name: "soluna" },
  { id: 25, name: "kuijra" },
  { id: 26, name: "angel-protocol" },
];
