/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const mainContainer = css({
  display: "flex",
  background: "pink",
  height: "100vh"
});

const navbar = css({
  display: "flex",
  flexDirection: "column",
  background: "green",
})

const contentContainer = css({
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  flex: "1 0 auto"
})



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={mainContainer}>
        {/* Left navigation bar */}
        <nav css={navbar}>
          {/* Main logo and link to home page */}
          <a href="/">Defi Llama</a>
          {/* Switch from DeFi to NFTs */}
          <div>
            <button>DeFi</button>
            <button>NFTs</button>
          </div>
          {/* Navigation */}
          <div>
            <div>Overview</div>
            <div>Chains</div>
            <div>Favourites</div>
            <div>About</div>
            <div>Overview</div>
          </div>
        </nav>
        {/* Main content, chart etc. */}
        <div css={contentContainer}>
          {/* Search bar */}
          <form>
            <input placeholder="Search..." />
          </form>
          {/* Container for info about TVL, change etc. */}
          <div>
            {/* TVL */}
            <div>
              <p>Total Value Locked (USD)</p>
              <p>50m</p>
            </div>
            {/* Change */}
            <div>
              <p>Change 24h</p>
              <p>50%</p>
            </div>
          </div>
          {/* Historical analysis chart */}
          <div>Total TVL</div>
          {/* Table */}
          <div>
            <p>TVL Rankings</p>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Chains</th>
                  <th>1d Change</th>
                  <th>7d Change</th>
                  <th>1m Change</th>
                </tr>
              </thead>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
