/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Navbar } from "../components/Navbar";
import { Table } from "../components/Table";

const mainContainer = css({
  display: "flex",
  background: "pink",
  height: "100vh",
});

const contentContainer = css({
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  flex: "1 0 auto",
});

const navbarWrapper = css({
  background:
    "linear-gradient(168deg, rgb(52, 65, 121) 3.98%, rgb(68, 94, 208) 100%)",
});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={mainContainer}>
        <div css={navbarWrapper}>
          <Navbar />
        </div>
        {/* Main content, chart etc. */}
        <div css={contentContainer}>
          {/* Table */}
          <Table />
        </div>
      </div>
    </div>
  );
};

export default Home;

// {/* Search bar */}
// <form>
//   <input placeholder="Search..." />
// </form>
// {/* Container for info about TVL, change etc. */}
// <div>
//   {/* TVL */}
//   <div>
//     <p>Total Value Locked (USD)</p>
//     <p>50m</p>
//   </div>
//   {/* Change */}
//   <div>
//     <p>Change 24h</p>
//     <p>50%</p>
//   </div>
// </div>
// {/* Historical analysis chart */}
// <div>Total TVL</div>
